cats99/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, only: [:index, :show, :new, :create, :edit, :update]
end

cats99/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cats99/app/models/cat.rb
class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper

  COLORS = ['red', 'white', 'brown', 'orange'] 
  validates :color, :inclusion => { :in => COLORS} 
  validates :sex, :inclusion => { :in => %w(M F)}

  def age
 
    time_ago_in_words(self.birth_date)
    
  end

end

cats99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

cats99/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index 
    @cats = Cat.all 
  end 

  def show
    @cat = Cat.find(params[:id])
  end

  def create
    @cat = Cat.new(cat_params)

    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def new
    @cat = Cat.new
  end

  def edit
    @cat = Cat.find(params[:id])
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  private
  def cat_params
    params[:cat].permit(
      :name, :birth_date, :color, :sex
    )
  end
end

cats99/app/helpers/application_helper.rb
module ApplicationHelper
end

cats99/app/helpers/cats_helper.rb
module CatsHelper
end

cats99/app/views/cats/_form.html.erb
<% if type == :new %>
    <% action_url = cats_url %>
    <% button_text = "Create kitty!" %>
<% elsif type == :edit %>
    <% action_url = cat_url(cat) %>
    <% button_text = "Update kitty" %>
<% end %>


<form action="<%= action_url %>" method="POST">
<% if type == :edit %> 
  <input type="hidden" name="_method" value="PATCH">
<%end%>
  <label>Name: 
    <input type="text" name="cat[name]" value="<%= cat.name %>"/>
  </label>
  <br>

  <label>Color: 
    <select name="cat[color]">
      <option value="<%= cat.color %>" selected>-- select a color --</option>
      <option value="orange">Orange</option>
      <option value="brown">Brown</option>
      <option value="white">White</option>
      <option value="red">Red</option>
    </select>
  </label>
   <br>

  <label>Birth Date: 
    <input type="date" name="cat[birth_date]" value="<%= cat.birth_date %>"/>
  </label>
   <br>

  <label>Sex:
    <% if cat.sex == "M" %> 
    <label>M<input type="radio" name="cat[sex]" value="M" checked/></label>
    <label>F<input type="radio" name="cat[sex]" value="F"/></label>
    <% else %>
    <label>M<input type="radio" name="cat[sex]" value="M"/></label>
    <label>F<input type="radio" name="cat[sex]" value="F" checked/></label>
    <% end %>
  </label>
   <br>

  <input type="submit" value="<%= button_text%>"/>
</form>

cats99/app/views/cats/edit.html.erb
<%= render "form", cat: @cat, type: :edit %>

<!-- > <form action="<%= cat_url(@cat) %>" method="POST">
# <input type="hidden" name="_method" value="PATCH">
#   <label>Name: 
#     <input type="text" name="cat[name]" value="<%= @cat.name %>"/>
#   </label>
#   <br>

#   <label>Color: 
#     <select name="cat[color]">
#       <option value="<%= @cat.color %>" selected>-- select a color --</option>
#       <option value="orange">Orange</option>
#       <option value="brown">Brown</option>
#       <option value="white">White</option>
#       <option value="red">Red</option>
#     </select>
#   </label>
#    <br>

#   <label>Birth Date: 
#     <input type="date" name="cat[birth_date]" value="<%= @cat.birth_date %>"/>
#   </label>
#    <br>

#   <label>Sex:
#     <% if @cat.sex == "M" %> 
#     <label>M<input type="radio" name="cat[sex]" value="M" checked/></label>
#     <label>F<input type="radio" name="cat[sex]" value="F"/></label>
#     <% else %>
#     <label>M<input type="radio" name="cat[sex]" value="M"/></label>
#     <label>F<input type="radio" name="cat[sex]" value="F" checked/></label>
#     <% end %>
#   </label>
#    <br>

#   <input type="submit" value="update kitty">
# </form>

cats99/app/views/cats/index.html.erb
<% @cats.each do |cat| %>
  <ul>
    <li><%= cat.name%></li>
    <li><%= cat.color%></li>
    <li><%= cat.birth_date%></li>
    <li><%= cat.sex%></li>
  </ul> 
<% end %>

cats99/app/views/cats/new.html.erb
<%= render "form", cat: @cat, type: :new %>



<!-- <form action="<%= cats_url %>" method="POST">
  <label>Name: 
    <input type="text" name="cat[name]" value=""/>
  </label>
  <br>

  <label>Color: 
    <select name="cat[color]">
      <option value="" selected>-- select a color --</option>
      <option value="orange">Orange</option>
      <option value="brown">Brown</option>
      <option value="white">White</option>
      <option value="red">Red</option>
    </select>
  </label>
   <br>

  <label>Birth Date: 
    <input type="date" name="cat[birth_date]" value=""/>
  </label>
   <br>

  <label>Sex: 
    <label>M<input type="radio" name="cat[sex]" value="M"/></label>
    <label>F<input type="radio" name="cat[sex]" value="F"/></label>
  </label>
   <br>

  <input type="submit" value="create kitty">
</form>

cats99/app/views/cats/show.html.erb
  <table>
  <thead>
      <tr>
        <td>Name   </td>
        <td>Color   </td>
        <td>Birth Date  </td>
        <td>Sex   </td>
      </tr></thead>
    <tbody>
  
      <tr>
        <td><%= @cat.name%></td>
        <td><%= @cat.color%></td>
        <td><%= @cat.birth_date%></td>
        <td><%= @cat.sex%></td>
      </tr>
    </tbody>
  </table> 

cats99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%#= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>